# Generated by Django 4.2.24 on 2025-09-23 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this account", max_length=100
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("access_token", models.CharField(max_length=500)),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_synced_history_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transaction_tag",
                    models.CharField(default="email-import", max_length=50),
                ),
                ("sender_filters", models.JSONField(blank=True, default=list)),
                ("keyword_filters", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gmail_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "email")},
            },
        ),
        migrations.DeleteModel(
            name="GoogleAccount",
        ),
    ]
