# Generated by Django 4.2.24 on 2025-09-24 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_account_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="goal",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="goal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("savings", "Savings Goal"),
                    ("spending", "Spending Goal"),
                    ("debt_payoff", "Debt Payoff"),
                    ("investment", "Investment Goal"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="GoalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_url", models.URLField(max_length=500)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("caption", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="finance.goal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["goal", "is_primary"],
                        name="finance_goa_goal_id_5f8532_idx",
                    )
                ],
            },
        ),
    ]
