# Generated by Django 4.2.24 on 2025-09-24 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0003_goal_color_goal_currency_goal_start_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatementImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("statement_period_start", models.DateField(blank=True, null=True)),
                ("statement_period_end", models.DateField(blank=True, null=True)),
                ("institution_name", models.CharField(blank=True, max_length=255)),
                ("account_number_masked", models.CharField(blank=True, max_length=50)),
                ("raw_text_content", models.TextField(blank=True)),
                ("parsed_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["statement_period_start"],
            },
        ),
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=20)),
                ("file_size", models.BigIntegerField()),
                ("file_hash", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_transactions", models.PositiveIntegerField(default=0)),
                ("successful_imports", models.PositiveIntegerField(default=0)),
                ("failed_imports", models.PositiveIntegerField(default=0)),
                ("duplicate_imports", models.PositiveIntegerField(default=0)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                ("processing_log", models.JSONField(blank=True, default=dict)),
                ("file_content", models.BinaryField(blank=True, null=True)),
                ("requires_password", models.BooleanField(default=False)),
                ("password_attempts", models.PositiveIntegerField(default=0)),
                ("ai_categorization_enabled", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_sessions",
                        to="finance.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("transfer", "Transfer"),
                            ("refund", "Refund"),
                            ("split_payment", "Split Payment"),
                            ("correction", "Correction"),
                            ("duplicate", "Duplicate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=5),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("auto_detected", models.BooleanField(default=True)),
                (
                    "from_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="finance.transaction",
                    ),
                ),
                (
                    "to_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="finance.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "import_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("imported", "Successfully Imported"),
                            ("duplicate", "Duplicate Detected"),
                            ("failed", "Import Failed"),
                            ("skipped", "Manually Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "parsed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("parsed_date", models.DateField(blank=True, null=True)),
                ("parsed_description", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "suggested_category_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("ai_merchant_detection", models.JSONField(blank=True, default=dict)),
                (
                    "statement_import",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_imports",
                        to="finance.statementimport",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_records",
                        to="finance.transaction",
                    ),
                ),
                (
                    "upload_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_imports",
                        to="finance.uploadsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["parsed_date", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="statementimport",
            name="upload_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statement_imports",
                to="finance.uploadsession",
            ),
        ),
        migrations.AddField(
            model_name="statementimport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="MerchantPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pattern", models.CharField(max_length=255)),
                ("merchant_name", models.CharField(blank=True, max_length=255)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0.5, max_digits=5),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_user_confirmed", models.BooleanField(default=False)),
                ("pattern_type", models.CharField(default="contains", max_length=20)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_patterns",
                        to="finance.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(
                fields=["user", "status"], name="finance_upl_user_id_e074b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(
                fields=["user", "account"], name="finance_upl_user_id_e1f4da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(
                fields=["file_hash"], name="finance_upl_file_ha_88e450_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(
                fields=["created_at"], name="finance_upl_created_bb01a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionlink",
            index=models.Index(
                fields=["from_transaction"], name="finance_tra_from_tr_d7f3a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionlink",
            index=models.Index(
                fields=["to_transaction"], name="finance_tra_to_tran_0e04bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionlink",
            index=models.Index(
                fields=["link_type"], name="finance_tra_link_ty_673c48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionlink",
            index=models.Index(
                fields=["is_confirmed"], name="finance_tra_is_conf_26500c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transactionlink",
            unique_together={("from_transaction", "to_transaction", "link_type")},
        ),
        migrations.AddIndex(
            model_name="transactionimport",
            index=models.Index(
                fields=["upload_session", "import_status"],
                name="finance_tra_upload__10ac75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionimport",
            index=models.Index(
                fields=["transaction"], name="finance_tra_transac_98ab26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionimport",
            index=models.Index(
                fields=["parsed_date"], name="finance_tra_parsed__962146_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchantpattern",
            index=models.Index(
                fields=["user", "is_active"], name="finance_mer_user_id_d01d3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchantpattern",
            index=models.Index(
                fields=["category"], name="finance_mer_categor_a78190_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchantpattern",
            index=models.Index(
                fields=["confidence"], name="finance_mer_confide_5674d4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="merchantpattern",
            unique_together={("user", "pattern")},
        ),
    ]
