# Generated by Django 4.2.24 on 2025-09-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_balancehistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["priority", "name"]},
        ),
        migrations.AddField(
            model_name="account",
            name="account_number_masked",
            field=models.CharField(
                blank=True, help_text="Masked account number for display", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="available_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Available balance excluding holds",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="closed_date",
            field=models.DateField(
                blank=True, help_text="Date account was closed", null=True
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="credit_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Credit limit for credit accounts",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="description",
            field=models.TextField(
                blank=True, help_text="Account description or notes"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="include_in_budget",
            field=models.BooleanField(
                default=True, help_text="Include in budget calculations"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="institution_code",
            field=models.CharField(
                blank=True, help_text="Bank/Institution routing code", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="interest_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Interest rate (annual %)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="Primary account for this type"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="last_sync_date",
            field=models.DateTimeField(
                blank=True, help_text="Last synchronization with institution", null=True
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional metadata"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="minimum_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Minimum required balance",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="opened_date",
            field=models.DateField(
                blank=True, help_text="Date account was opened", null=True
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("closed", "Closed"),
                    ("frozen", "Frozen"),
                    ("pending", "Pending"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="tags",
            field=models.JSONField(
                blank=True, default=list, help_text="Tags for categorization"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="track_balance",
            field=models.BooleanField(default=True, help_text="Track balance changes"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["user", "status"], name="finance_acc_user_id_bf5e91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["priority"], name="finance_acc_priorit_9280da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["institution"], name="finance_acc_institu_10b466_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["is_primary"], name="finance_acc_is_prim_af0bd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["opened_date"], name="finance_acc_opened__d40c98_idx"
            ),
        ),
    ]
