# Generated by Django 4.2.24 on 2025-09-26 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "finance",
            "0006_alter_account_options_account_account_number_masked_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField(help_text="Year (e.g., 2024)")),
                ("month", models.PositiveIntegerField(help_text="Month (1-12)")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Account balance at end of month",
                        max_digits=12,
                    ),
                ),
                (
                    "statement_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Balance from bank statement",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Difference between recorded and statement balance",
                        max_digits=12,
                    ),
                ),
                (
                    "reconciled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the balance has been reconciled",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this monthly balance entry"
                    ),
                ),
                (
                    "entry_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this entry was created"
                    ),
                ),
                (
                    "total_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total income for the month",
                        max_digits=12,
                    ),
                ),
                (
                    "total_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total expenses for the month",
                        max_digits=12,
                    ),
                ),
                (
                    "calculated_change",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Calculated balance change (income - expenses)",
                        max_digits=12,
                    ),
                ),
                (
                    "actual_change",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual balance change from previous month",
                        max_digits=12,
                    ),
                ),
                (
                    "missing_transactions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated missing transactions",
                        max_digits=12,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_balances",
                        to="finance.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["account", "-year", "-month"],
                        name="finance_mon_account_c5a122_idx",
                    ),
                    models.Index(
                        fields=["user", "-year", "-month"],
                        name="finance_mon_user_id_2b5764_idx",
                    ),
                    models.Index(
                        fields=["reconciled"], name="finance_mon_reconci_f685d7_idx"
                    ),
                    models.Index(
                        fields=["difference"], name="finance_mon_differe_f72d54_idx"
                    ),
                ],
                "unique_together": {("user", "account", "year", "month")},
            },
        ),
    ]
