# Generated by Django 4.2.24 on 2025-09-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_balancerecord"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="monthlybalance",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="monthlybalance",
            name="account",
        ),
        migrations.RemoveField(
            model_name="monthlybalance",
            name="user",
        ),
        migrations.AddField(
            model_name="goal",
            name="thumbnail_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name="BalanceHistory",
        ),
        migrations.DeleteModel(
            name="MonthlyBalance",
        ),
    ]
