# Generated by Django 4.2.24 on 2025-09-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="google_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="google_profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
