# Generated by Django 4.2.24 on 2025-09-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile_bio_userprofile_email_notifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_photos/thumbnails/"
            ),
        ),
    ]
